type: python
framework: fastapi
path: services/foo

runtime:
  port: 8004
  entry_point: main:app
  python_version: "3.11"

schemas:
  mount_dir: models

dependencies:
  services:
    - bar
  # TODO:
  # permitir filtrar os schemas que podem acionar o renício do serviço
  # se "schemas" não estiver definido no campo "dependencies", o serviço "dependerá" de todos
  # reiniciando o serviço caso qualquer schema mude, do contrário apenas os listados irão reiniciaá-lo.
  schemas:
    - message
